### ISSUE TITLE
Where is the evaluation loop for a single individual over all training cases?

### ISSUE THREAD

**Issue by Vaguery** [lspector/propeller#72]
I have seen that `interpreter.cljc` runs one individual vs one training case. I am writing an observation to disk immediately after that is completed. And it's working.

But I need to start a new CSV row after each individual has been evaluated over all the training cases.

Where is the actual code that evaluates one individual over all training cases?

I've looked for about an hour at `gp.cljc` and I am not seeing it. Is it tucked into a `let` clause somewhere? Is it in some sort of `if` branch? Both of those?

That file is honestly a remarkably difficult artifact to understand.

**Comment by Vaguery** [comment]
Oh it's in `error-function` isn't it?

**Comment by lspector** [comment]
Yes, a typical `error-function` will run `interpreter/interpret-program` for all of the training cases.
